import type { CollectionEntry } from "astro:content";

export type Lang = "ko" | "en";
export const DEFAULT_LANG: Lang = "ko";
export const SUPPORTED_LANGS: readonly Lang[] = ["ko", "en"] as const;

/**
 * Derive the language of a blog post from its entry id.
 * IDs generated by Astro glob loader include the subfolder path.
 * e.g. `ko/fems-project-log-01` → "ko"
 *      `en/fems-project-log-01` → "en"
 *      `some-legacy-flat` → default lang
 */
export function getLang(entry: CollectionEntry<"blog">): Lang {
  const firstSegment = entry.id.split("/")[0];
  if (firstSegment === "en") return "en";
  if (firstSegment === "ko") return "ko";
  return DEFAULT_LANG;
}

/**
 * Return the language-stripped slug of a post.
 * e.g. `ko/fems-project-log-01` → "fems-project-log-01"
 */
export function stripLangPrefix(id: string): string {
  const segments = id.split("/");
  if (segments.length > 1 && (segments[0] === "ko" || segments[0] === "en")) {
    return segments.slice(1).join("/");
  }
  return id;
}

/**
 * Filter a post collection to a single language.
 */
export function filterByLang(
  posts: CollectionEntry<"blog">[],
  lang: Lang
): CollectionEntry<"blog">[] {
  return posts.filter(post => getLang(post) === lang);
}
