import type { CollectionEntry } from "astro:content";

export type Lang = "ko" | "en";
export const DEFAULT_LANG: Lang = "ko";
export const SUPPORTED_LANGS: readonly Lang[] = ["ko", "en"] as const;

/**
 * Derive the language of a blog post from its entry id.
 * IDs generated by Astro glob loader include the subfolder path.
 * e.g. `ko/fems-project-log-01` → "ko"
 *      `en/fems-project-log-01` → "en"
 *      `some-legacy-flat` → default lang
 */
export function getLang(entry: CollectionEntry<"blog">): Lang {
  const firstSegment = entry.id.split("/")[0];
  if (firstSegment === "en") return "en";
  if (firstSegment === "ko") return "ko";
  return DEFAULT_LANG;
}

/**
 * Return the language-stripped slug of a post.
 * e.g. `ko/fems-project-log-01` → "fems-project-log-01"
 */
export function stripLangPrefix(id: string): string {
  const segments = id.split("/");
  if (segments.length > 1 && (segments[0] === "ko" || segments[0] === "en")) {
    return segments.slice(1).join("/");
  }
  return id;
}

/**
 * Filter a post collection to a single language.
 */
export function filterByLang(
  posts: CollectionEntry<"blog">[],
  lang: Lang
): CollectionEntry<"blog">[] {
  return posts.filter(post => getLang(post) === lang);
}

/**
 * 포스트가 아닌 고정 페이지(홈 · About 등)의 hreflang 대체 링크를 만든다.
 *
 * 포스트 상세는 PostDetails.astro 가 KO/EN 짝을 찾아 직접 계산하지만, 고정 페이지는
 * 짝이 경로로 이미 정해져 있어 그냥 만들어주면 된다. 이게 없으면 구글이 / 와 /en/ 을
 * 서로의 번역본으로 인식하지 못한다.
 *
 * x-default 는 사이트 기본 언어인 한국어를 가리킨다.
 */
export function staticHreflang(
  koPath: string,
  enPath: string,
  site: string
): { lang: string; href: string }[] {
  const ko = new URL(koPath, site).href;
  const en = new URL(enPath, site).href;
  return [
    { lang: "ko", href: ko },
    { lang: "en", href: en },
    { lang: "x-default", href: ko },
  ];
}
